/**
 * Computes one InterHand2.6M subject's `PriorSourcePair` (via `buildSubjectPrior.ts`, run once per
 * hand) and writes it as a committed TypeScript module under `../fitted/` -- a real `PriorSource`,
 * browser-loadable via a plain `import` (unlike the raw `external-data/interhand26m/` dataset this
 * reads from, which is gitignored and only ever touched by Bun scripts with filesystem access, never by
 * any browser page).
 *
 * Run with: bun run src/routes/scan3/lib/priors/interhand/generateFittedSubject.ts [subjectId]
 *
 * One file per SUBJECT, not per hand -- see `priorSource.ts`'s `PriorSourcePair` doc comment for why a
 * source's two hands travel together as one unit rather than being two independently-selectable rows.
 * Attempts both `Right` and `Left`; a hand this subject/split doesn't have frames for is logged and
 * simply left `undefined` in the pair rather than failing the whole run.
 *
 * This never touches `handModelData.ts` -- see `buildSubjectPrior.ts`'s own doc comment. Re-run any
 * time to regenerate a subject's file (e.g. after a fitting-method change); each subject's file is
 * fully independent of every other's and of the literature seed.
 */

import type { PartialHandPriorState } from '../priorSource'
import { buildSubjectPrior } from './buildSubjectPrior'
import { fitBoneLengths } from './fitBoneLengths'
import { fitDipPipCoupling } from './fitDipPipCoupling'
import { fitMcpChoke } from './fitMcpChoke'
import { fitRom } from './fitRom'
import { loadSubjectFrames } from './loadFrames'

const SUBJECT_ID = process.argv[2] ?? '0'
const HANDS: { key: 'right' | 'left'; cap: 'Right' | 'Left' }[] = [
  { key: 'right', cap: 'Right' },
  { key: 'left', cap: 'Left' },
]

async function fitOneHand(cap: 'Right' | 'Left', key: 'right' | 'left'): Promise<{ data: PartialHandPriorState; frames: number; seqs: number } | undefined> {
  let frames
  try {
    frames = await loadSubjectFrames('train', SUBJECT_ID, key)
  } catch (e) {
    console.log(`  ${cap}: no data (${(e as Error).message})`)
    return undefined
  }
  if (frames.length === 0) {
    console.log(`  ${cap}: 0 valid frames -- skipped`)
    return undefined
  }
  const seqs = new Set(frames.map(f => f.seq))
  const label = `interhand-${SUBJECT_ID}-${key}`

  const bones = fitBoneLengths(frames)
  const rom = fitRom(frames)
  const dipPip = fitDipPipCoupling(frames)
  const mcpChoke = fitMcpChoke(frames, cap)
  for (const m of mcpChoke) {
    console.log(`  ${cap} mcpChoke.${m.finger}: shrinkageCorrelation=${m.shrinkageCorrelation.toFixed(2)} fitted=${m.fitted}${m.fitted ? ` chokeCoeff=${m.chokeCoeff!.toFixed(4)}` : ''}`)
  }
  return { data: buildSubjectPrior(label, bones, rom, dipPip, mcpChoke), frames: frames.length, seqs: seqs.size }
}

async function main() {
  const results: Partial<Record<'Right' | 'Left', { data: PartialHandPriorState; frames: number; seqs: number }>> = {}
  for (const { key, cap } of HANDS) {
    const result = await fitOneHand(cap, key)
    if (result) results[cap] = result
  }

  if (!results.Right && !results.Left) {
    console.error(`Subject ${SUBJECT_ID}: no usable data for either hand -- nothing written`)
    process.exit(1)
  }

  const generatedAt = new Date().toISOString().slice(0, 10)
  const summary = (['Right', 'Left'] as const)
    .map(h => (results[h] ? `${h}: ${results[h]!.frames} frames, ${results[h]!.seqs} sequences` : `${h}: no data`))
    .join('; ')

  const dataEntries = (['Right', 'Left'] as const)
    .filter(h => results[h])
    .map(h => `  ${h}: ${JSON.stringify(results[h]!.data, null, 2).split('\n').join('\n  ')},`)
    .join('\n')

  const out = `/**
 * GENERATED by generateFittedSubject.ts on ${generatedAt} -- do not hand-edit; re-run the script
 * instead. Subject ${SUBJECT_ID}, InterHand2.6M 'train' split -- ${summary}. See buildSubjectPrior.ts
 * for exactly what this does and doesn't cover per hand, and priorSource.ts's PriorSourcePair doc
 * comment for why both hands travel together in one source rather than as two selectable rows.
 */

import type { PriorSource } from '../priorSource'

export const INTERHAND_${SUBJECT_ID}_SOURCE: PriorSource = {
  id: 'interhand-${SUBJECT_ID}',
  label: 'InterHand2.6M subject ${SUBJECT_ID}',
  sourceType: 'interhand',
  description: '${summary}. Bone lengths, PIP/DIP ROM + DIP/PIP coupling (index/middle/ring/pinky), and MCP ab/ad choke coefficient where the shrinkage check passed -- see buildSubjectPrior.ts.',
  data: {
${dataEntries}
  },
}
`

  const outPath = `${import.meta.dir}/../fitted/interhand-${SUBJECT_ID}.ts`
  await Bun.write(outPath, out)
  console.log(`Wrote ${outPath} (${summary})`)
}

main()
