/**
 * GENERATED by generateFittedSubject.ts on 2026-09-07 -- do not hand-edit; re-run the script
 * instead. Subject 0, InterHand2.6M 'train' split -- Right: 417 frames, 44 sequences; Left: 426 frames, 43 sequences. See buildSubjectPrior.ts
 * for exactly what this does and doesn't cover per hand, and priorSource.ts's PriorSourcePair doc
 * comment for why both hands travel together in one source rather than as two selectable rows.
 */

import type { PriorSource } from '../priorSource'

export const INTERHAND_0_SOURCE: PriorSource = {
  id: 'interhand-0',
  label: 'InterHand2.6M subject 0',
  sourceType: 'interhand',
  description:
    'Right: 417 frames, 44 sequences; Left: 426 frames, 43 sequences. Bone lengths, PIP/DIP ROM + DIP/PIP coupling (index/middle/ring/pinky), and MCP ab/ad choke coefficient where the shrinkage check passed -- see buildSubjectPrior.ts.',
  data: {
    Right: {
      'boneLengths': {
        'handLength': {
          'mean': 190.9921971829831,
          'variance': 15.354163952950605,
          'source': "interhand-0-right: within-subject fit, n=359 frames -- this subject's own absolute hand size, not a population average",
        },
        'fingers': {
          'thumb': {
            'segments': [
              'wristToCmc',
              'metacarpal',
              'proximal',
              'distal',
            ],
            'mean': [
              0.23895580161823715,
              0.19114122353387678,
              0.17228005170937433,
              0.14970902582580167,
            ],
            'covariance': [
              [
                0.00009117507856927322,
                0,
                0,
                0,
              ],
              [
                0,
                0.00016049461679967577,
                0,
                0,
              ],
              [
                0,
                0,
                0.00011117840306275796,
                0,
              ],
              [
                0,
                0,
                0,
                0.00003769350144439396,
              ],
            ],
            'source': 'interhand-0-right: within-subject fit, n=[359, 359, 359, 355] frames per segment, excluded=[58, 58, 58, 62] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'indexFinger': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.48804689744782515,
              0.21967623581498705,
              0.13262900628475266,
              0.12355085435763818,
            ],
            'covariance': [
              [
                0.00011136808515087249,
                0,
                0,
                0,
              ],
              [
                0,
                0.00010816229920831977,
                0,
                0,
              ],
              [
                0,
                0,
                0.000028963781797139678,
                0,
              ],
              [
                0,
                0,
                0,
                0.000045520832662416154,
              ],
            ],
            'source': 'interhand-0-right: within-subject fit, n=[359, 359, 359, 359] frames per segment, excluded=[58, 58, 58, 58] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'middleFinger': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.4723376511097735,
              0.23672320842051114,
              0.15933086571735416,
              0.13160827475236117,
            ],
            'covariance': [
              [
                0.00022342915702450246,
                0,
                0,
                0,
              ],
              [
                0,
                0.00024427053495740025,
                0,
                0,
              ],
              [
                0,
                0,
                0.000030169317276808726,
                0,
              ],
              [
                0,
                0,
                0,
                0.00008816595985854144,
              ],
            ],
            'source': 'interhand-0-right: within-subject fit, n=[359, 359, 359, 359] frames per segment, excluded=[58, 58, 58, 58] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'ringFinger': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.4609432511063713,
              0.22466157337127513,
              0.15237725142278408,
              0.12784653703173224,
            ],
            'covariance': [
              [
                0.00031861394878745695,
                0,
                0,
                0,
              ],
              [
                0,
                0.00022191295043791104,
                0,
                0,
              ],
              [
                0,
                0,
                0.00003247024040196354,
                0,
              ],
              [
                0,
                0,
                0,
                0.00011932693398400963,
              ],
            ],
            'source': 'interhand-0-right: within-subject fit, n=[359, 359, 359, 353] frames per segment, excluded=[58, 58, 58, 64] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'pinky': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.4542388047762175,
              0.1721647706221219,
              0.11063423030290397,
              0.10882738227561183,
            ],
            'covariance': [
              [
                0.0003039426079010941,
                0,
                0,
                0,
              ],
              [
                0,
                0.00007395627834432596,
                0,
                0,
              ],
              [
                0,
                0,
                0.000018118798826564235,
                0,
              ],
              [
                0,
                0,
                0,
                0.00007108407490859582,
              ],
            ],
            'source': 'interhand-0-right: within-subject fit, n=[359, 359, 359, 357] frames per segment, excluded=[58, 58, 58, 60] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
        },
        'knuckleRow': {
          'mean': [
            0.13758736825811088,
            0.12867148840858814,
            0.12613506356996534,
          ],
          'covariance': [
            [
              0.000039637248167225844,
              0,
              0,
            ],
            [
              0,
              0.00004813895490899113,
              0,
            ],
            [
              0,
              0,
              0.00004227220510911056,
            ],
          ],
          'source':
            "interhand-0-right: within-subject fit, n=359 frames, excluded by gap (segment-consistency filter): [58, 58, 58] -- straight-line MCP-to-MCP distance (docs/thumbs/interhand-2-average.md Stage 3a's method, applied cross-finger)",
        },
      },
      'pipDipRom': {
        'pip': {
          'indexFinger': {
            'minDeg': 1.6235599521908426,
            'maxDeg': 104.2953122280376,
            'meanDeg': 26.98503908618351,
            'sdDeg': 32.65691173721826,
            'source': 'interhand-0-right: within-subject fit, n=417 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'middleFinger': {
            'minDeg': 1.2131090793539137,
            'maxDeg': 101.04787639339811,
            'meanDeg': 32.25857310330074,
            'sdDeg': 35.71318797037113,
            'source': 'interhand-0-right: within-subject fit, n=417 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'ringFinger': {
            'minDeg': 0.37338514822889124,
            'maxDeg': 103.61902341569164,
            'meanDeg': 39.81696501184334,
            'sdDeg': 38.380796920177566,
            'source': 'interhand-0-right: within-subject fit, n=417 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'pinky': {
            'minDeg': 0.21675942291161218,
            'maxDeg': 98.70894411603145,
            'meanDeg': 34.103932144241256,
            'sdDeg': 33.07504476230644,
            'source': 'interhand-0-right: within-subject fit, n=417 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
        },
        'dip': {
          'indexFinger': {
            'minDeg': 0.23706695809072234,
            'maxDeg': 59.16216096790726,
            'meanDeg': 10.890873257623324,
            'sdDeg': 15.718139724546457,
            'source': 'interhand-0-right: within-subject fit, n=417 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'middleFinger': {
            'minDeg': 0.17314059101389612,
            'maxDeg': 76.66523495874141,
            'meanDeg': 11.60070036570832,
            'sdDeg': 15.989862593021122,
            'source': 'interhand-0-right: within-subject fit, n=359 frames, 58 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'ringFinger': {
            'minDeg': 1.277808531416904,
            'maxDeg': 74.5610697731248,
            'meanDeg': 13.109212693939119,
            'sdDeg': 16.22130312523671,
            'source': 'interhand-0-right: within-subject fit, n=360 frames, 57 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'pinky': {
            'minDeg': 1.0724418673161717,
            'maxDeg': 57.17782761652865,
            'meanDeg': 12.291511224266616,
            'sdDeg': 14.072352565010593,
            'source': 'interhand-0-right: within-subject fit, n=393 frames, 24 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
        },
      },
      'dipPipCoupling': {
        'indexFinger': {
          'mean': [
            0.4064768007216198,
            -0.07791909747641057,
          ],
          'covariance': [
            [
              0.00016008952031932423,
              -0.004320021963105334,
            ],
            [
              -0.004320021963105334,
              0.28730725408422847,
            ],
          ],
          'source': 'interhand-0-right: within-subject OLS fit, n=417 frames (0 excluded), R^2=0.713 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
        'middleFinger': {
          'mean': [
            0.5479189211930302,
            -0.3337031880630956,
          ],
          'covariance': [
            [
              0.0002000637377055045,
              -0.004357654554171176,
            ],
            [
              -0.004357654554171176,
              0.23255335680417344,
            ],
          ],
          'source': 'interhand-0-right: within-subject OLS fit, n=359 frames (58 excluded), R^2=0.808 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
        'ringFinger': {
          'mean': [
            0.3983386748098341,
            1.066383695083461,
          ],
          'covariance': [
            [
              0.00026765418072696685,
              -0.008091891983278981,
            ],
            [
              -0.008091891983278981,
              0.5213768227307587,
            ],
          ],
          'source': 'interhand-0-right: within-subject OLS fit, n=360 frames (57 excluded), R^2=0.623 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
        'pinky': {
          'mean': [
            0.4047861812877409,
            -0.05855983036952672,
          ],
          'covariance': [
            [
              0.00012185242689311013,
              -0.0037177309895369747,
            ],
            [
              -0.0037177309895369747,
              0.22752299286171224,
            ],
          ],
          'source': 'interhand-0-right: within-subject OLS fit, n=393 frames (24 excluded), R^2=0.775 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
      },
      'mcpAxes': {
        'ringFinger': {
          'abAdChokeCoeff': {
            'mean': 0.026312645411376692,
            'variance': 0.0006487491546222859,
            'source':
              "interhand-0-right: within-subject fit under an ASSUMED shared axis convention (palmBasisAxes' sagittal-plane deviation, not a per-subject calibrated axis) -- shrinkage correlation -0.39 across 8 flexion bins (docs/thumbs/interhand-2-average.md Stage 3c). Treat as lower-confidence than bone lengths/ROM/DIP-PIP coupling above.",
          },
        },
        'pinky': {
          'abAdChokeCoeff': {
            'mean': 0.23331410880180783,
            'variance': 0.005815680561477946,
            'source':
              "interhand-0-right: within-subject fit under an ASSUMED shared axis convention (palmBasisAxes' sagittal-plane deviation, not a per-subject calibrated axis) -- shrinkage correlation -0.78 across 8 flexion bins (docs/thumbs/interhand-2-average.md Stage 3c). Treat as lower-confidence than bone lengths/ROM/DIP-PIP coupling above.",
          },
        },
      },
    },
    Left: {
      'boneLengths': {
        'handLength': {
          'mean': 191.80018122220636,
          'variance': 19.60273567336859,
          'source': "interhand-0-left: within-subject fit, n=384 frames -- this subject's own absolute hand size, not a population average",
        },
        'fingers': {
          'thumb': {
            'segments': [
              'wristToCmc',
              'metacarpal',
              'proximal',
              'distal',
            ],
            'mean': [
              0.23700227128990303,
              0.19352306984296117,
              0.1695853655383692,
              0.151572433848175,
            ],
            'covariance': [
              [
                0.00008362582302136037,
                0,
                0,
                0,
              ],
              [
                0,
                0.00018213572423019683,
                0,
                0,
              ],
              [
                0,
                0,
                0.00009083894246233905,
                0,
              ],
              [
                0,
                0,
                0,
                0.00004099210623648261,
              ],
            ],
            'source': 'interhand-0-left: within-subject fit, n=[384, 384, 384, 372] frames per segment, excluded=[42, 42, 42, 54] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'indexFinger': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.4958724339458636,
              0.22171866305420404,
              0.13086485896220051,
              0.12092309938197213,
            ],
            'covariance': [
              [
                0.00014739973175027893,
                0,
                0,
                0,
              ],
              [
                0,
                0.00011209606657216852,
                0,
                0,
              ],
              [
                0,
                0,
                0.000019901435529658956,
                0,
              ],
              [
                0,
                0,
                0,
                0.000051315618167240194,
              ],
            ],
            'source': 'interhand-0-left: within-subject fit, n=[384, 384, 384, 383] frames per segment, excluded=[42, 42, 42, 43] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'middleFinger': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.47931814795068645,
              0.23804933921956575,
              0.15347169571353145,
              0.12916081711621688,
            ],
            'covariance': [
              [
                0.00020462012103198142,
                0,
                0,
                0,
              ],
              [
                0,
                0.0001699319926730702,
                0,
                0,
              ],
              [
                0,
                0,
                0.00002553302596837331,
                0,
              ],
              [
                0,
                0,
                0,
                0.0001022368041067785,
              ],
            ],
            'source': 'interhand-0-left: within-subject fit, n=[384, 384, 384, 384] frames per segment, excluded=[42, 42, 42, 42] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'ringFinger': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.46832943922189085,
              0.21705047616059212,
              0.1460543443477075,
              0.13286848789004604,
            ],
            'covariance': [
              [
                0.00044537495595883993,
                0,
                0,
                0,
              ],
              [
                0,
                0.00037010747005503884,
                0,
                0,
              ],
              [
                0,
                0,
                0.00003276502891577968,
                0,
              ],
              [
                0,
                0,
                0,
                0.00010860642271559108,
              ],
            ],
            'source': 'interhand-0-left: within-subject fit, n=[384, 384, 384, 368] frames per segment, excluded=[42, 42, 42, 58] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
          'pinky': {
            'segments': [
              'metacarpal',
              'proximal',
              'middle',
              'distal',
            ],
            'mean': [
              0.44985999004910177,
              0.16368977317862962,
              0.10792988956183114,
              0.11134001822451312,
            ],
            'covariance': [
              [
                0.0004212193372022642,
                0,
                0,
                0,
              ],
              [
                0,
                0.00014189342547269587,
                0,
                0,
              ],
              [
                0,
                0,
                0.00001528079484595327,
                0,
              ],
              [
                0,
                0,
                0,
                0.0000690489010488853,
              ],
            ],
            'source': 'interhand-0-left: within-subject fit, n=[384, 384, 384, 373] frames per segment, excluded=[42, 42, 42, 53] (docs/thumbs/interhand-2-average.md Stage 3a)',
          },
        },
        'knuckleRow': {
          'mean': [
            0.13327688745979036,
            0.12275184311832833,
            0.12996105089777057,
          ],
          'covariance': [
            [
              0.00002693143033375022,
              0,
              0,
            ],
            [
              0,
              0.00004135421379572267,
              0,
            ],
            [
              0,
              0,
              0.00005101154675460486,
            ],
          ],
          'source':
            "interhand-0-left: within-subject fit, n=383 frames, excluded by gap (segment-consistency filter): [42, 42, 43] -- straight-line MCP-to-MCP distance (docs/thumbs/interhand-2-average.md Stage 3a's method, applied cross-finger)",
        },
      },
      'pipDipRom': {
        'pip': {
          'indexFinger': {
            'minDeg': 0.8264545118739869,
            'maxDeg': 108.48137833032084,
            'meanDeg': 29.904550822189965,
            'sdDeg': 31.403907534128983,
            'source': 'interhand-0-left: within-subject fit, n=426 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'middleFinger': {
            'minDeg': 0.6349363806799821,
            'maxDeg': 103.90310771471101,
            'meanDeg': 31.116600209957504,
            'sdDeg': 33.53674457451469,
            'source': 'interhand-0-left: within-subject fit, n=426 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'ringFinger': {
            'minDeg': 0.3420818487275299,
            'maxDeg': 102.20183582364331,
            'meanDeg': 37.02379525480996,
            'sdDeg': 35.23048133705553,
            'source': 'interhand-0-left: within-subject fit, n=426 frames, 0 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'pinky': {
            'minDeg': 0.6637644011244173,
            'maxDeg': 97.86317384891042,
            'meanDeg': 26.723531041594654,
            'sdDeg': 32.35114229973116,
            'source': 'interhand-0-left: within-subject fit, n=425 frames, 1 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
        },
        'dip': {
          'indexFinger': {
            'minDeg': 0.48440171101454255,
            'maxDeg': 58.27790566415434,
            'meanDeg': 10.620110467975866,
            'sdDeg': 14.738717986488561,
            'source': 'interhand-0-left: within-subject fit, n=425 frames, 1 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'middleFinger': {
            'minDeg': 0.3170398700029761,
            'maxDeg': 68.94352675951001,
            'meanDeg': 13.596969565425825,
            'sdDeg': 18.054509204485615,
            'source': 'interhand-0-left: within-subject fit, n=384 frames, 42 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'ringFinger': {
            'minDeg': 1.0109696226003166,
            'maxDeg': 74.63788676634738,
            'meanDeg': 12.80254817765934,
            'sdDeg': 17.45248685471965,
            'source': 'interhand-0-left: within-subject fit, n=375 frames, 51 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
          'pinky': {
            'minDeg': 0.7750293561969487,
            'maxDeg': 63.587106897485064,
            'meanDeg': 12.854532704336135,
            'sdDeg': 17.982579926538918,
            'source': 'interhand-0-left: within-subject fit, n=402 frames, 24 excluded by segment-consistency check (docs/thumbs/interhand-2-average.md Stage 3d)',
          },
        },
      },
      'dipPipCoupling': {
        'indexFinger': {
          'mean': [
            0.42480085861236033,
            -2.0074778236762096,
          ],
          'covariance': [
            [
              0.00010014203122114037,
              -0.0029768121116352524,
            ],
            [
              -0.0029768121116352524,
              0.1861198714554503,
            ],
          ],
          'source': 'interhand-0-left: within-subject OLS fit, n=425 frames (1 excluded), R^2=0.810 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
        'middleFinger': {
          'mean': [
            0.6101820009237621,
            -0.8524320175400124,
          ],
          'covariance': [
            [
              0.00026872566608858467,
              -0.006363552282901718,
            ],
            [
              -0.006363552282901718,
              0.33511259741523325,
            ],
          ],
          'source': 'interhand-0-left: within-subject OLS fit, n=384 frames (42 excluded), R^2=0.784 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
        'ringFinger': {
          'mean': [
            0.4810217244871457,
            -1.07100379197289,
          ],
          'covariance': [
            [
              0.00034109865149558775,
              -0.009837912982705562,
            ],
            [
              -0.009837912982705562,
              0.5734579923483113,
            ],
          ],
          'source': 'interhand-0-left: within-subject OLS fit, n=375 frames (51 excluded), R^2=0.645 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
        'pinky': {
          'mean': [
            0.5527731432507034,
            0.0765250844182983,
          ],
          'covariance': [
            [
              0.00016972629258214553,
              -0.003923424801648592,
            ],
            [
              -0.003923424801648592,
              0.23766242975784385,
            ],
          ],
          'source': 'interhand-0-left: within-subject OLS fit, n=402 frames (24 excluded), R^2=0.818 (docs/thumbs/interhand-2-average.md Stage 3b)',
        },
      },
      'mcpAxes': {
        'indexFinger': {
          'abAdChokeCoeff': {
            'mean': 0.11246768300701299,
            'variance': 0.006989638679831547,
            'source':
              "interhand-0-left: within-subject fit under an ASSUMED shared axis convention (palmBasisAxes' sagittal-plane deviation, not a per-subject calibrated axis) -- shrinkage correlation -0.48 across 8 flexion bins (docs/thumbs/interhand-2-average.md Stage 3c). Treat as lower-confidence than bone lengths/ROM/DIP-PIP coupling above.",
          },
        },
        'middleFinger': {
          'abAdChokeCoeff': {
            'mean': 0.030928119838865932,
            'variance': 0.0006707620552344366,
            'source':
              "interhand-0-left: within-subject fit under an ASSUMED shared axis convention (palmBasisAxes' sagittal-plane deviation, not a per-subject calibrated axis) -- shrinkage correlation -0.44 across 8 flexion bins (docs/thumbs/interhand-2-average.md Stage 3c). Treat as lower-confidence than bone lengths/ROM/DIP-PIP coupling above.",
          },
        },
        'ringFinger': {
          'abAdChokeCoeff': {
            'mean': 0.08660967484365263,
            'variance': 0.000964829740567742,
            'source':
              "interhand-0-left: within-subject fit under an ASSUMED shared axis convention (palmBasisAxes' sagittal-plane deviation, not a per-subject calibrated axis) -- shrinkage correlation -0.75 across 8 flexion bins (docs/thumbs/interhand-2-average.md Stage 3c). Treat as lower-confidence than bone lengths/ROM/DIP-PIP coupling above.",
          },
        },
        'pinky': {
          'abAdChokeCoeff': {
            'mean': 0.19994130692771117,
            'variance': 0.01363697266741268,
            'source':
              "interhand-0-left: within-subject fit under an ASSUMED shared axis convention (palmBasisAxes' sagittal-plane deviation, not a per-subject calibrated axis) -- shrinkage correlation -0.57 across 8 flexion bins (docs/thumbs/interhand-2-average.md Stage 3c). Treat as lower-confidence than bone lengths/ROM/DIP-PIP coupling above.",
          },
        },
      },
    },
  },
}
